title: Théo Ladune
logo: /assets/img/profile_picture.png
description: PhD student @ Orange Labs / INSA Rennes
interest: My work focuses on novel deep learning-based coding schemes for image and video compression.
show_downloads: false
mail: mailto:theo.ladune@orange.com
scholar: https://scholar.google.com/citations?user=sp2hQtcAAAAJ&hl=fr
linkedin: https://www.linkedin.com/in/theo-ladune/
theme: jekyll-theme-minimal

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: false